// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Splitza.Api.Data;

#nullable disable

namespace Splitza.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260308163229_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Splitza.Api.Models.BillSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("ZAR");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DiscountAllocation")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PaymentMode")
                        .HasColumnType("integer");

                    b.Property<decimal>("ServiceFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServiceFeeAllocation")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tip")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipAllocation")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Vat")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("BillSessions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "ZAR",
                            Discount = 0m,
                            DiscountAllocation = 1,
                            Name = "Demo — Harbour House",
                            PaymentMode = 0,
                            ServiceFee = 0m,
                            ServiceFeeAllocation = 0,
                            Status = 4,
                            Subtotal = 520.00m,
                            Tip = 78.00m,
                            TipAllocation = 1,
                            Total = 598.00m,
                            UpdatedAt = new DateTime(2025, 1, 1, 12, 30, 0, 0, DateTimeKind.Utc),
                            Vat = 0m
                        });
                });

            modelBuilder.Entity("Splitza.Api.Models.ItemAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AllocationType")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityPortion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ReceiptItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("ReceiptItemId");

                    b.ToTable("ItemAllocations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            AllocationType = 0,
                            Amount = 260.00m,
                            PersonId = new Guid("22222222-2222-2222-2222-222222222222"),
                            QuantityPortion = 0m,
                            ReceiptItemId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            AllocationType = 0,
                            Amount = 120.00m,
                            PersonId = new Guid("33333333-3333-3333-3333-333333333333"),
                            QuantityPortion = 0m,
                            ReceiptItemId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            AllocationType = 1,
                            Amount = 70.00m,
                            PersonId = new Guid("22222222-2222-2222-2222-222222222222"),
                            QuantityPortion = 1m,
                            ReceiptItemId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            AllocationType = 1,
                            Amount = 70.00m,
                            PersonId = new Guid("33333333-3333-3333-3333-333333333333"),
                            QuantityPortion = 1m,
                            ReceiptItemId = new Guid("66666666-6666-6666-6666-666666666666")
                        });
                });

            modelBuilder.Entity("Splitza.Api.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BillSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsHost")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BillSessionId");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BillSessionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsHost = true,
                            Name = "Alice"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BillSessionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsHost = false,
                            Name = "Bob"
                        });
                });

            modelBuilder.Entity("Splitza.Api.Models.ReceiptItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BillSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsManuallyAdded")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BillSessionId");

                    b.ToTable("ReceiptItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            BillSessionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsManuallyAdded = false,
                            LineTotal = 260.00m,
                            Name = "Grilled Kingklip",
                            Quantity = 1m,
                            SortOrder = 1,
                            UnitPrice = 260.00m
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            BillSessionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsManuallyAdded = false,
                            LineTotal = 120.00m,
                            Name = "Calamari Starter",
                            Quantity = 1m,
                            SortOrder = 2,
                            UnitPrice = 120.00m
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            BillSessionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsManuallyAdded = false,
                            LineTotal = 140.00m,
                            Name = "House Wines x2",
                            Quantity = 2m,
                            SortOrder = 3,
                            UnitPrice = 70.00m
                        });
                });

            modelBuilder.Entity("Splitza.Api.Models.ItemAllocation", b =>
                {
                    b.HasOne("Splitza.Api.Models.Person", "Person")
                        .WithMany("Allocations")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Splitza.Api.Models.ReceiptItem", "ReceiptItem")
                        .WithMany("Allocations")
                        .HasForeignKey("ReceiptItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("ReceiptItem");
                });

            modelBuilder.Entity("Splitza.Api.Models.Person", b =>
                {
                    b.HasOne("Splitza.Api.Models.BillSession", "BillSession")
                        .WithMany("People")
                        .HasForeignKey("BillSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillSession");
                });

            modelBuilder.Entity("Splitza.Api.Models.ReceiptItem", b =>
                {
                    b.HasOne("Splitza.Api.Models.BillSession", "BillSession")
                        .WithMany("Items")
                        .HasForeignKey("BillSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillSession");
                });

            modelBuilder.Entity("Splitza.Api.Models.BillSession", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("People");
                });

            modelBuilder.Entity("Splitza.Api.Models.Person", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("Splitza.Api.Models.ReceiptItem", b =>
                {
                    b.Navigation("Allocations");
                });
#pragma warning restore 612, 618
        }
    }
}
